eureka:
  instance:
<<<<<<< HEAD
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
=======
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/
>>>>>>> ac2834074424d7e6db8661edfaf3735bc0ffceeb

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
<<<<<<< HEAD
    host: rabbitmq
=======
    host: localhost
    port: 5672
>>>>>>> ac2834074424d7e6db8661edfaf3735bc0ffceeb
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

authserver:
<<<<<<< HEAD
    hostname: auth-service
=======
    hostname: localhost
>>>>>>> ac2834074424d7e6db8661edfaf3735bc0ffceeb
    port: 5000
    contextPath: /uaa

security:
  oauth2:
    resource:
<<<<<<< HEAD
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
=======
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
>>>>>>> ac2834074424d7e6db8661edfaf3735bc0ffceeb
